### PR TITLE
update GI to reflect current hive block weight

### PR DESCRIPTION
**Pull request by ghost**
The community has seen that GI does not show accurate view of profit potential.  This is primarily due to number of hive blocks consistently at 33.3% instead of 50.0% as originally planned.  The community has created a "Honey" index that is based on this new index to accurately show potential profits in hives.  I am suggesting import of this index as well as the future index (based on number of current immature bees that will mature) for users to make more accurate decisions when purchasing.  It will also cause GI to not inflate as much and people to not understand why they are not profiting when GI says they will.  I understand this can take time to analyze and potential other reasons, but being on the 3rd wave of bee purchases I don't think this will even out unless it is changed in the wallet.  This will also allow community members to grow and be able to understand profits without having to go to community for explanation that GI is more like gambling at this point.   It is my understanding that hive to PoW block ratio will not change based on the time it takes for PoW blocks to come in versus consensus of hive blocks, and it has been consistent since hive activation on mainnet.

### CODE REVIEW

**Comment by coldcity** [comment]
Don't change nomenclature pointlessly -- too many knock-on effects. Just revise GI down to the new expectation.

**Comment by ghost** [comment]
I think keeping GI name is fine if it is incorporated into wallet..  just confusing to community if they see different GI numbers.

**Comment by shadow-42** [comment]
Consensus is that this is a bug and changing the GI won't fix the problem just hide it, utilize other community indexes until a resolution is found (very close) 👍

**Comment by ghost** [comment]
Forcing hive block to 50:50 would require idle POW so GI should be modified as well as honey pot lowered to ~13mil like in my original request.

**Comment by ghost** [comment]
fixed in 16.0.5 :)

**Pull request closed without merging**
