### PR TITLE
Draft Implementation of a multi-threaded Hive miner

### PR DESCRIPTION
**Pull request by MerlinMagic2018**
- Faster bee's hashes iteration
- This means more bees can be mining optimally on a single wallet / CPU
- Starts to mine faster when a new block is found.

### CODE REVIEW

**Review by MerlinMagic2018 — COMMENTED** [review]
This is for 8 threads. Automatic CPU cores detection could be added.

**Comment by litecoincash-project** [comment]
Thanks for this. We're not going to approve as-is, as this needs to be configurable, but we'll incorporate in our current 0.16.1.2 work as needed (wip now).

**Comment by MerlinMagic2018** [comment]
Cool thx.

**Comment by litecoincash-project** [comment]
I see where you're going with this, but you still have race conditions and lack of parameterisation.

**Comment by blockester** [comment]
Did these changes improve your Hive mining results?

**Comment by litecoincash-project** [comment]
Implemented (in a different manner)

**Pull request closed without merging**
